### PR TITLE
A new form with multiple fields that stores data in console

### PR DESCRIPTION
**Pull request by andreamogren**

### CODE REVIEW

**Comment by AngelicaRuth** [comment]
It's a good start, but I think from a user experience that it would be better to type in my numbers instead of using the up and down arrows.

**Comment by andreamogren** [comment]
You don't have to use the arrows, you can just type in any number you want :) At least that is how it is on my computer... 

I haven't really styled it yet since I want to wait until I know what kind of design we're going for. :)

**Comment by AngelicaRuth** [comment]
You'll have to be able to insert data that has decimals as well.

**Comment by andreamogren** [comment]
On my end decimal numbers work? 😮

**Pull request closed without merging**
